vncviewer: 'vncviewer'
vncargs: '-Shared -FullColor -PreferredEncoding=ZRLE -AutoSelect=0'
soundplayer: 'soundplay-107098-8.6.3-linux-x86_64'
aplay: '/usr/bin/play -q -v %v %s '
window_size: [1280, 800]
window_positions: [[0, 0], [1280, 0], [0, 1280], [1280, 0]]
