#!/bin/bash

#activate conda environment
# NOTE: The KRO environment is created with: conda env create -f environment.yaml
CONDA_BASE=$(conda info --base)
source $CONDA_BASE/etc/profile.d/conda.sh
conda activate KRO
#NOTE: old method using 'source' will work too but not preferred
#source activeate KRO

#change to script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

#launch 
pytest

