#!/bin/bash
# NOTE: The KRO environment is created with: conda env create -f environment.yaml

CONDA=`which conda 2> /dev/null`

if [ "$CONDA" != "" ]; then
    CONDA_BASE=$(conda info --base)
    source $CONDA_BASE/etc/profile.d/conda.sh
    conda activate KRO
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

#launch
python3 test_basic_connectivity.py
